### PR TITLE
Fix ToString to correctly handle disposed streams.

### LINKED ISSUE #242: RecyclableMemoryStream.ToString should not throw if disposed
From https://docs.microsoft.com/en-us/dotnet/api/system.object.tostring?view=net-6.0
Notes to Inheritors
Your [ToString()](https://docs.microsoft.com/en-us/dotnet/api/system.object.tostring?view=net-6.0#system-object-tostring) override should not throw an exception.

This comes up for us in unit tests that use moq. it remembers all invocations and their parameters and, if a verification failure happens, it will ToString all of the parameters to make the error report but in the case of Stream arguments, if it was a RecyclableMemoryStream that has long since been disposed, the exception from its ToString prevents meaningful diagnostics from moq.

### PR DESCRIPTION
**Pull request by benmwatson**
Resolves #242 

Fix `RecyclableMemoryStream.ToString` to show status of disposable, and some still-valid info after the stream is disposed.

### CODE REVIEW

File: src/RecyclableMemoryStream.cs [hunk 1]
```diff
@@ -1087,7 +1087,15 @@ public override void Write(ReadOnlySpan<byte> source)
...
         public override string ToString()
         {
-            return $"Id = {this.Id}, Tag = {this.Tag}, Length = {this.Length:N0} bytes";
+            if (!this.disposed)
+            {
+                return $"Id = {this.Id}, Tag = {this.Tag}, Length = {this.Length:N0} bytes";
+            }
+            else
+            {
+                // Avoid properties because of the dispose check, but the fields themselves are not cleared.
```
Comment (grbell-ms) [inline src/RecyclableMemoryStream.cs:1096]: This is also true of the `length` field. We could add the final length or something to the string.

**Review by grbell-ms — APPROVED** [review]
