### PR TITLE
Fix bug with CopyToAsync not adjusting source position

### LINKED ISSUE #139: CopyToAsync reset source stream position
We found strange behaviour change between 1.4.0 and previous version at **CopyToAsync** method. At version 1.4.0 this method reset (IMO unexpectedly) the SOURCE stream position back to position before call.

### PR DESCRIPTION
**Pull request by benmwatson**
Resolves #139 

The RMS version incorrectly kept the stream's position at the pre-copy value, when the correct behavior according to `MemoryStream`s implementation is to in fact increment the position as if it were a read operation.

This PR resolves this bug and adds some unit tests to ensure all code paths are hit.

### CODE REVIEW

File: src/RecyclableMemoryStream.cs [hunk 1]
```diff
@@ -592,15 +596,16 @@ public override Task CopyToAsync(Stream destination, int bufferSize, Cancellatio
                     if (this.blocks.Count == 1)
                     {
                         AssertLengthIsSmall();
-                        return destination.WriteAsync(this.blocks[0], (int)this.position, (int)(this.length - this.position), cancellationToken);
+                        return destination.WriteAsync(this.blocks[0], (int)this.position, (int)count, cancellationToken).ContinueWith((task) => this.position += count);
```
Comment (grbell-ms) [inline src/RecyclableMemoryStream.cs:599]: We can avoid creating a continuation by advancing the position first. (This is what MemoryStream does.)
```suggestion
                        var pos = this.position;
                        this.position += count;
                        return destination.WriteAsync(this.blocks[0], (int)pos, (int)count, cancellationToken);
```

File: src/RecyclableMemoryStream.cs [hunk 2]
```diff
@@ -612,13 +617,14 @@ async Task CopyToAsyncImpl(CancellationToken ct)
...
                             }
+                            this.position += totalBytesToWrite;
                         }
                     }
                 }
                 else
                 {
                     AssertLengthIsSmall();
-                    return destination.WriteAsync(this.largeBuffer, (int)this.position, (int)(this.length - this.position), cancellationToken);
+                    return destination.WriteAsync(this.largeBuffer, (int)this.position, (int)count, cancellationToken).ContinueWith((task) => this.position += count);
```
Comment (grbell-ms) [inline src/RecyclableMemoryStream.cs:627]: Same thing here.
